---
title: "Using collector() for large data sets"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using collector() for large data sets}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---




Some of our datasets are large and moving them from that database to your computer can take a fair amount of time.  So long in fact that is not uncommon for our connections to die.^[I don't really understand why this happens].  Additionally, you tend not to get a lot of feedback when using `dplyr`'s `collect()` function to return the data to your computer. It either gets the data silently or dies trying.

For this reason, `ideadata` has a `collector()` function.  It's used the same way as `collect`, but requires you to pass parameters (i.e., column names for the table you are trying to collect ) that are used to break your data into pieces based on the set of values within the columns you identify. 

Consider the `StudentDailyAttendance` table on `PROD1`

```r
devtools::load_all(".")
#> ℹ Loading ideadata
#> ── Gathering warehouse metadata ─────────────────────────────────────────────── ideadata 3.0.1 ──
#> ℹ Checking credentials ...
#> christopher.haid's Kereberos TGT is current
#> ✓ Success: Warehouse metadata gathered!
#> ℹ The warehouse currently houses:
#>      2,226 tables
#>   in 134 databases
#>   on 17 servers
#> YOW! ideadata and you are honestly polished!
#library(ideadata)
library(dplyr)
library(lubridate)

stu_attendance  <- get_student_daily_attendance()

glimpse(stu_attendance)
#> Rows: ??
#> Columns: 50
#> Database: Microsoft SQL Server 15.00.4153[IPS\christopher.haid@REDACTED-SQLSERVER/PROD1]
#> $ AcademicYear         [3m[38;5;246m<chr>[39m[23m "2019-2020", "2019-2020", "2019-2020", "2019-2020", "2019-2020", "…
#> $ SchoolTermID         [3m[38;5;246m<dbl>[39m[23m 2900, 2900, 2900, 2900, 2900, 2900, 2900, 2900, 2900, 2900, 2900, …
#> $ SchoolName           [3m[38;5;246m<chr>[39m[23m "IDEA Oscar Dunn Academy", "IDEA Oscar Dunn Academy", "IDEA Bridge…
#> $ schoolnumber         [3m[38;5;246m<dbl>[39m[23m 19001, 19001, 917002, 19001, 917004, 917004, 917005, 19001, 19001,…
#> $ StateSchoolNumber    [3m[38;5;246m<dbl>[39m[23m 19001, 19001, 17048, 19001, 17049, 17049, 17049, 19001, 19001, 170…
#> $ SchoolShortName      [3m[38;5;246m<chr>[39m[23m "Oscar Dunn", "Oscar Dunn", "Bridge", "Oscar Dunn", "Innovation", …
#> $ SchoolType           [3m[38;5;246m<chr>[39m[23m "Academy", "Academy", "College Prep", "Academy", "Academy", "Acade…
#> $ VPofSchools          [3m[38;5;246m<dbl>[39m[23m 7218, 7218, 7218, 7218, 19402, 19402, 19402, 7218, 7218, 19402, 72…
#> $ VPofSchoolsName      [3m[38;5;246m<chr>[39m[23m "Kathryn Patterson", "Kathryn Patterson", "Kathryn Patterson", "Ka…
#> $ RegionID             [3m[38;5;246m<dbl>[39m[23m 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, …
#> $ RegionDescription    [3m[38;5;246m<chr>[39m[23m "Southern Louisiana", "Southern Louisiana", "Southern Louisiana", …
#> $ GradeLevelID         [3m[38;5;246m<dbl>[39m[23m 5, 1, 7, 5, 1, 2, 6, 0, 0, 0, 3, 0, 7, 1, 0, 1, 3, 0, 4, 0, 7, 6, …
#> $ GradeLevel           [3m[38;5;246m<chr>[39m[23m "5", "1", "7", "5", "1", "2", "6", "K", "K", "K", "3", "K", "7", "…
#> $ AttStudentKey        [3m[38;5;246m<dbl>[39m[23m 25763666, 25763718, 25763742, 25763770, 25853496, 25853514, 258535…
#> $ StudentNumber        [3m[38;5;246m<dbl>[39m[23m 101001386, 101002376, 101001981, 101001340, 101001899, 101000944, …
#> $ FirstName            [3m[38;5;246m<chr>[39m[23m "Keili", "Jeremiah", "Ligia", "Riheem", "Kylie", "Tarr", "Nikolas"…
#> $ LastName             [3m[38;5;246m<chr>[39m[23m "Adams", "De Silva", "Gomez Rivas", "Westerfield", "Carpenter", "B…
#> $ FullName             [3m[38;5;246m<chr>[39m[23m "Adams, Keili Lyrics", "De Silva, Jeremiah", "Gomez Rivas, Ligia E…
#> $ WeekNumber           [3m[38;5;246m<chr>[39m[23m "11", "11", "11", "11", "12", "12", "12", "12", "12", "13", "13", …
#> $ DateNumber           [3m[38;5;246m<int>[39m[23m 52, 52, 52, 52, 54, 54, 54, 54, 54, 61, 61, 60, 60, 60, 60, 60, 60…
#> $ AttDate              [3m[38;5;246m<date>[39m[23m 2019-10-18, 2019-10-18, 2019-10-18, 2019-10-18, 2019-10-22, 2019-…
#> $ Membership           [3m[38;5;246m<dbl>[39m[23m 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
#> $ Absences             [3m[38;5;246m<dbl>[39m[23m 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
#> $ VAbsences            [3m[38;5;246m<dbl>[39m[23m 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
#> $ SPED                 [3m[38;5;246m<int>[39m[23m 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
#> $ ELL                  [3m[38;5;246m<int>[39m[23m 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
#> $ LEP                  [3m[38;5;246m<int>[39m[23m 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
#> $ Farm                 [3m[38;5;246m<int>[39m[23m 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
#> $ CSI                  [3m[38;5;246m<int>[39m[23m 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, …
#> $ NonSpedEllCsi        [3m[38;5;246m<int>[39m[23m 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, …
#> $ Ethnicity            [3m[38;5;246m<chr>[39m[23m "Black-African-American", "Black-African-American", "White", "Blac…
#> $ Hispanic             [3m[38;5;246m<int>[39m[23m 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, …
#> $ ContinuouslyEnrolled [3m[38;5;246m<chr>[39m[23m "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "1", "0", "0", "…
#> $ AtRisk               [3m[38;5;246m<int>[39m[23m 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, …
#> $ PersistenceType      [3m[38;5;246m<int>[39m[23m 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
#> $ SchoolYear           [3m[38;5;246m<chr>[39m[23m "1", "1", "2+", "1", "2+", "2+", "2+", "1", "1", "2+", "2+", "2+",…
#> $ DayAfterEvent        [3m[38;5;246m<chr>[39m[23m NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
#> $ EventDate            [3m[38;5;246m<date>[39m[23m NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
#> $ MaxTempinF           [3m[38;5;246m<dbl>[39m[23m 75, 75, 75, 75, 77, 77, 77, 77, 77, 75, 75, 83, 83, 83, 83, 83, 83…
#> $ AvgTempInF           [3m[38;5;246m<dbl>[39m[23m 63.5, 63.5, 63.5, 63.5, 61.2, 61.2, 61.2, 61.2, 61.2, 53.8, 53.8, …
#> $ MinTempInF           [3m[38;5;246m<dbl>[39m[23m 58, 58, 58, 58, 0, 0, 0, 0, 0, 42, 42, 68, 68, 68, 68, 68, 68, 68,…
#> $ CompareKey           [3m[38;5;246m<chr>[39m[23m "7218|Kathryn Patterson|6|Southern Louisiana|2900|19001|5|10100138…
#> $ RdoEmployeeID        [3m[38;5;246m<dbl>[39m[23m 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
#> $ RdoEmployeeName      [3m[38;5;246m<chr>[39m[23m "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""…
#> $ SchoolTypeOperation  [3m[38;5;246m<chr>[39m[23m NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
#> $ Enroll               [3m[38;5;246m<int>[39m[23m 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
#> $ Area                 [3m[38;5;246m<chr>[39m[23m NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
#> $ SubRegionID          [3m[38;5;246m<dbl>[39m[23m NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
#> $ SubRegionDescription [3m[38;5;246m<chr>[39m[23m NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
#> $ Instance             [3m[38;5;246m<chr>[39m[23m "LA", "LA", "LA", "LA", "LA", "LA", "LA", "LA", "LA", "LA", "LA", …
```

```r

#school years are stored as characters, which is inefficient for filtering
# TermIDs are doubles (thought they really ought be integers), but are 
# much faster for filtering. 

term_id <- calc_ps_termid(2022)


stu_attend_2021 <- stu_attendance %>% 
  filter(SchoolTermID == term_id)

n_rows <- stu_attend_2021 %>% 
  count() %>% 
  pull()

n_rows
#> [1] 0
```
So as of the June 02, 2022 there are 0	student attendance records. That will be a tall order for `collect` so instead lets use `collector`.

`collector` takes column names, uses thosecolumns to get all combinations of variables that appear in the data, and then uses those combinations to pull your data down in smaller chunks defined be each combination (e.g., for each school and data, as shown below). 


```r
collection_data_start <- today() - days(2)

stu_attend_2021_temp <- stu_attendance %>% 
  select(StudentNumber, AttDate, schoolnumber , Membership, Absences) %>% 
  filter(AttDate >= '2021-10-08', 
         SchoolNumber %in% c('108807186', '108807187', '108807302', '109907024')) %>%  

  compute()
#> Created a temporary table named #dbplyr_005

 
stu_attend_2021_collected <-  stu_attend_2021_temp %>% 
  collector(AttDate, schoolnumber) %>% 
  janitor::clean_names()
#> Collecting data
#> 
#> Pulling data filtered to: AttDate == '2021-10-08', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-10-08', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-10-08', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-10-08', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-10-12', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-10-12', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-10-12', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-10-12', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-10-13', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-10-13', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-10-13', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-10-13', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-10-14', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-10-14', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-10-14', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-10-14', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-10-18', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-10-18', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-10-18', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-10-18', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-10-19', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-10-19', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-10-19', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-10-19', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-10-20', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-10-20', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-10-20', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-10-20', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-10-21', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-10-21', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-10-21', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-10-21', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-10-22', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-10-22', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-10-22', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-10-22', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-10-25', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-10-25', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-10-25', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-10-25', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-10-26', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-10-26', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-10-26', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-10-26', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-10-27', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-10-27', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-10-27', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-10-27', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-10-28', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-10-28', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-10-28', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-10-28', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-10-29', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-10-29', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-10-29', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-10-29', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-11-01', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-11-01', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-11-01', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-11-01', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-11-02', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-11-02', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-11-02', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-11-02', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-11-03', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-11-03', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-11-03', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-11-03', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-11-04', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-11-04', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-11-04', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-11-04', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-11-05', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-11-05', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-11-05', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-11-05', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-11-08', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-11-08', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-11-08', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-11-08', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-11-09', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-11-09', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-11-09', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-11-09', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-11-10', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-11-10', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-11-10', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-11-10', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-11-11', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-11-11', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-11-11', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-11-11', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-11-12', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-11-12', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-11-12', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-11-12', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-11-15', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-11-15', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-11-15', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-11-15', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-11-16', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-11-16', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-11-16', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-11-16', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-11-17', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-11-17', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-11-17', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-11-17', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-11-18', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-11-18', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-11-18', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-11-18', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-11-19', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-11-19', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-11-19', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-11-19', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-11-29', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-11-29', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-11-29', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-11-29', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-11-30', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-11-30', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-11-30', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-11-30', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-12-01', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-12-01', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-12-01', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-12-01', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-12-02', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-12-02', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-12-02', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-12-02', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-12-03', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-12-03', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-12-03', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-12-03', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-12-06', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-12-06', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-12-06', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-12-06', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-12-07', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-12-07', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-12-07', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-12-07', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-12-08', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-12-08', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-12-08', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-12-08', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-12-09', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-12-09', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-12-09', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-12-09', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-12-10', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-12-10', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-12-10', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-12-10', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-12-13', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-12-13', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-12-13', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-12-13', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-12-14', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-12-14', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-12-14', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-12-14', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-12-15', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-12-15', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-12-15', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-12-15', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-12-16', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-12-16', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-12-16', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-12-16', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2021-12-17', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2021-12-17', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2021-12-17', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2021-12-17', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-04', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-04', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-04', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-04', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-05', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-05', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-05', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-05', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-06', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-06', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-06', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-06', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-07', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-07', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-07', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-07', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-10', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-10', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-10', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-10', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-11', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-11', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-11', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-11', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-12', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-12', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-12', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-12', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-13', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-13', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-13', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-13', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-14', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-14', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-14', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-14', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-18', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-18', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-18', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-18', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-19', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-19', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-19', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-19', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-20', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-20', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-20', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-20', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-21', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-21', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-21', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-21', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-24', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-24', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-24', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-24', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-25', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-25', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-25', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-25', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-26', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-26', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-26', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-26', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-27', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-27', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-27', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-27', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-28', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-28', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-28', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-28', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-01-31', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-01-31', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-01-31', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-01-31', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-02-01', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-02-01', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-02-01', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-02-01', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-02-02', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-02-02', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-02-02', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-02-02', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-02-07', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-02-07', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-02-07', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-02-07', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-02-08', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-02-08', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-02-08', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-02-08', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-02-09', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-02-09', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-02-09', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-02-09', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-02-10', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-02-10', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-02-10', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-02-10', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-02-11', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-02-11', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-02-11', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-02-11', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-02-14', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-02-14', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-02-14', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-02-14', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-02-15', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-02-15', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-02-15', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-02-15', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-02-16', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-02-16', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-02-16', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-02-16', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-02-17', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-02-17', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-02-17', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-02-17', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-02-18', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-02-18', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-02-18', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-02-18', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-02-22', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-02-22', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-02-22', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-02-22', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-02-23', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-02-23', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-02-23', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-02-23', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-02-28', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-02-28', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-02-28', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-02-28', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-03-01', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-03-01', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-03-01', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-03-01', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-03-02', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-03-02', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-03-02', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-03-02', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-03-03', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-03-03', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-03-03', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-03-03', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-03-04', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-03-04', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-03-04', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-03-04', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-03-07', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-03-07', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-03-07', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-03-07', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-03-08', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-03-08', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-03-08', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-03-08', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-03-09', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-03-09', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-03-09', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-03-09', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-03-10', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-03-10', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-03-10', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-03-10', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-03-21', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-03-21', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-03-21', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-03-21', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-03-22', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-03-22', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-03-22', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-03-22', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-03-23', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-03-23', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-03-23', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-03-23', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-03-24', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-03-24', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-03-24', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-03-24', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-03-25', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-03-25', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-03-25', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-03-25', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-03-28', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-03-28', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-03-28', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-03-28', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-03-29', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-03-29', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-03-29', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-03-29', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-03-30', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-03-30', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-03-30', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-03-30', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-03-31', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-03-31', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-03-31', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-03-31', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-01', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-01', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-01', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-01', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-04', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-04', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-04', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-04', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-05', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-05', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-05', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-05', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-06', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-06', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-06', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-06', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-07', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-07', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-07', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-07', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-08', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-08', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-08', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-08', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-11', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-11', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-11', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-11', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-12', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-12', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-12', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-12', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-13', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-13', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-13', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-13', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-14', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-14', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-14', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-14', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-18', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-18', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-18', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-18', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-19', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-19', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-19', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-19', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-20', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-20', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-20', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-20', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-21', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-21', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-21', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-21', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-22', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-22', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-22', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-22', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-25', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-25', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-25', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-25', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-26', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-26', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-26', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-26', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-27', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-27', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-27', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-27', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-28', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-28', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-28', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-28', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-04-29', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-04-29', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-04-29', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-04-29', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-05-02', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-05-02', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-05-02', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-05-02', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-05-03', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-05-03', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-05-03', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-05-03', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-05-04', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-05-04', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-05-04', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-05-04', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-05-05', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-05-05', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-05-05', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-05-05', schoolnumber == '109907024' ...
#> Pulling data filtered to: AttDate == '2022-05-06', schoolnumber == '108807186' ...
#> Pulling data filtered to: AttDate == '2022-05-06', schoolnumber == '108807187' ...
#> Pulling data filtered to: AttDate == '2022-05-06', schoolnumber == '108807302' ...
#> Pulling data filtered to: AttDate == '2022-05-06', schoolnumber == '109907024' ...
#> Data collection complete
```



Note the call to `dplyr::compute()` in the code above (highlighted).



What is that `compute()` call doing?

`compute()` forces the database to evaluate all the prior steps (i.e. a filter, a select, and another filter), after which the will create a temporary table there (i.e., a table which get's deleted when your conenction closes.  

Wihout this step each iteration created by `collector()` (via `purrr::map_df()`) will re run the the magrittr pipeline, of which the tw filter steps are computationally expensive. 
A caveat with this desing pattern is you need to have permissions to write temporary tables to the database.  If you can't do that, then you'll have to suffer the pain of waiting for the DB to run all of your `magrittr` pipeline (i.e., all the stuff following each `%>%`) for each iteration.  

In any case, here are the results of the call, witht eh student numbers masked by an sha1 cryptohash:


```r
stu_attend_2021_feb %>% 
  head(20) %>% 
  mutate(student_number = openssl::sha1(as.character(student_number))) %>% #crypto hash
  knitr::kable()
#> Error in head(., 20): object 'stu_attend_2021_feb' not found
```

Notice that the table `stu_attendance` (i.e, `STudentDailyAttendance` on `PROD1`) has 50 columns.  A trick used above is to reduce  the columns to only those you need to use later with a `select` statement early in the data pipeline; doing so greatly reduces the amount of data you are requesting from the database. 
