# GitHub Actions Workflow - Self-Hosted Runner (Full Test Suite)
#
# This workflow runs on a self-hosted runner inside IDEA network
# Runs ALL tests including database integration tests
#
# To use:
# 1. Set up self-hosted runner inside IDEA network
# 2. Configure database credentials on runner machine
# 3. Move this file to .github/workflows/ (remove -examples)
# 4. Commit and push

name: R-CMD-check (Full Test Suite)

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]
  workflow_dispatch:  # Allow manual trigger

jobs:
  check:
    runs-on: self-hosted  # Runs on your internal runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install system dependencies (if Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Query R dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install R dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Check package
        run: |
          rcmdcheck::rcmdcheck(
            args = c("--no-manual", "--as-cran"),
            error_on = "warning",
            check_dir = "check"
          )
        shell: Rscript {0}

      - name: Run full test suite
        run: |
          # Database credentials should be in .Renviron on runner machine
          cat("Running full test suite (including database tests)\n")
          devtools::test()
        shell: Rscript {0}

      - name: Test coverage
        run: |
          covr::package_coverage()
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: check-results
          path: check
